# Generated by Django 5.0.6 on 2024-07-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0025_alter_processingrun_consultation"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultationfile",
            name="file_path",
            field=models.CharField(default="", editable=False),
            preserve_default=False,
        ),
    ]
