# Generated by Django 5.1.4 on 2024-12-30 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0027_delete_existing_consultation_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="theme",
            name="topic_model_metadata",
        ),
        migrations.DeleteModel(
            name="TopicModelMetadata",
        ),
    ]
