# Generated by Django 5.1.4 on 2024-12-30 16:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0027_delete_existing_consultation_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topicmodelmetadata",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="theme",
            name="unique_id_per_model",
        ),
        migrations.RemoveField(
            model_name="topicmodelmetadata",
            name="scatter_plot_data",
        ),
    ]
