# Generated by Django 5.1.4 on 2024-12-30 16:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0028_alter_topicmodelmetadata_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="theme",
            name="topic_model_metadata",
        ),
        migrations.DeleteModel(
            name="TopicModelMetadata",
        ),
    ]
