# Generated by Django 5.1.4 on 2024-12-30 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0029_remove_theme_topic_model_metadata_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="theme",
            options={"ordering": ["created_at"]},
        ),
    ]
